### ISSUE TITLE
Using this with Eclipse

### ISSUE THREAD

**Issue by DiogoTavaresDeAlmeidaRibeiro** [cnicodeme/play2.2-subproject#1]
I've downloaded and imported this to eclipse.

Eclipse identifies the three modules but doesn't identify the global project.

Any help?

Thanks

**Comment by neowinx** [comment]
You have to tell to the eclipse task that don't skip the parent when it generates the eclipse project files:

```bash
eclipse skip-parents=false
```

**Comment by DiogoTavaresDeAlmeidaRibeiro** [comment]
Thanks a lot neowinx. Worked like a charm.
